remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: My Vim And Neovim Configuration
author: Toma Brasoveanu
exclude:
  - _config.yml
  - Gemfile
  - LICENSE
rss-description: Vim Configuration
plugins:
  - jekyll-responsive_image
  - jekyll-include-cache
  - emoji_for_jekyll
