theme: minimal-mistakes-jekyll
title: My Vim Configuration
author: Toma Brasoveanu
exclude:
  - _config.yml
  - LICENSE
rss-description: Vim Configuration
plugins:
  - jekyll-responsive_image
  - jekyll-include-cache
  - emoji_for_jekyll
